### ISSUE TITLE
Question regarding glow.

### ISSUE THREAD

**Issue by LennDG** [GDQuest/godot-visual-effects#1]
I realize this might not be the best place to ask questions but I could not find where I should ask them.

In the LaserBeam demo project, there is a glow effect on the particles and beam. I figured out that this glow is the result of the WorldEnvironment glow setting and a CanvasItem setting on the beam and particles. The WorldEnvironment I have figured out but I cannot find how to change the CanvasItem modulation to 
![image](https://user-images.githubusercontent.com/5593865/82884730-69cf3080-9f44-11ea-97b4-eed0092e83d6.png)

I can only input values up to 255 when I try to change it. Could you tell me how this different modulation is achieved?

Thanks.

**Comment by LennDG** [comment]
Figured it out eventually, you have to switch on and then off again the "raw" slider. I have no idea why though.

**Comment by NathanLovato** [comment]
It's due to the HDR threshold. The glow post-processing effect makes pixels with a value above that threshold glow by default, and it's set to 1, meaning pure white, a color of Vector3(1.0, 1.0, 1.0). The raw button allows you to get past that, reaching values beyond 1.0.
