### ISSUE TITLE
Link off main page to contributor guidelines is a 404

### ISSUE THREAD

**Issue by graydwarf** [GDQuest/godot-visual-effects#14]
https://www.gdquest.com/docs/guidelines/contributing-to/gdquest-projects/

I've got a few fixes lined up including one for the laser example. Wanted to make sure you're still accepting PRs for this project.

**Comment by NathanLovato** [comment]
Just added a redirect to the new location of the page to our website, it's rebuilding now and this will be fixed shortly. Thanks for the heads-up!
