### ISSUE TITLE
Bug: Collision Normal on LaserBeamDemo is not correct.

### ISSUE THREAD

**Issue by LennDG** [GDQuest/godot-visual-effects#2]
**I'm submitting a...**

- [X ] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**

When firing the laser at asteroids on the left, up and down of the player ship the collision particles do not fly according to the CollisionNormal.

**What is the expected behavior?**
The particles should fire back along the direction of the beam.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

If you place one of the asteroids under, above or left of the player ship you can see this behaviour.

**Comment by NathanLovato** [comment]
Confirmed, I'm on it!
